### PR TITLE
Fix: TypeError when calling repr() on AMQPError

### PR DESCRIPTION
**Pull request by rupa108**
self.args sometimes has more the one element

### CODE REVIEW

**Comment by taybin** [comment]
We're seeing this as well.  Could this get merged?

**Comment by mosquito** [comment]
@rupa108 @taybin sorry but after its was merged it but CI pipeline has been failed. I have to revert it. If it's still actual please reopen PR.

**Comment by taybin** [comment]
What was the failure?

**Comment by mosquito** [comment]
Failed [pipeline](https://github.com/mosquito/aiormq/runs/1258997774?check_suite_focus=true) here

**Pull request merged**
